# Nome do executável
TARGET = montador.exe

# Regra padrão
all: $(TARGET)

# Compilação
$(TARGET): main.c
	gcc -Wall main.c -o $(TARGET) -lm

# Regra para rodar (No Windows usamos .\ e o nome do arquivo)
run: $(TARGET)
	.\$(TARGET) entrada.asm

# Limpeza (Comandos do Windows: del /f /q)
clean:
	if exist $(TARGET) del /f /q $(TARGET)
	if exist *.o del /f /q *.o