# Nome do executável
TARGET = montador

# Arquivos fonte
SRC = main.c funcoes.c

# Compilador
CC = gcc

# Flags de compilação
CFLAGS = -Wall

# Regra padrão
all: $(TARGET)

# Compilação
$(TARGET): $(SRC)
	$(CC) $(CFLAGS) $(SRC) -o $(TARGET)

# Executar o programa
run: $(TARGET)
	./$(TARGET)

# Limpar arquivos gerados
clean:
	rm -f $(TARGET) *.o